INSERT INTO CATS(caption, parent_id) VALUES('Маленький', 1);
INSERT INTO CATS(caption, parent_id) VALUES('Кофе', 1);
INSERT INTO CATS(caption, parent_id) VALUES('Гор. шок.', 1);
INSERT INTO CATS(caption, parent_id) VALUES('Другие напитки', 1);
INSERT INTO CATS(caption, parent_id) VALUES('Средний', 5);
INSERT INTO CATS(caption, parent_id) VALUES('Кофе', 5);
INSERT INTO CATS(caption, parent_id) VALUES('Гор. шок.', 5);
INSERT INTO CATS(caption, parent_id) VALUES('Другие напитки', 5);
INSERT INTO CATS(caption, parent_id) VALUES('Большой', 9);
INSERT INTO CATS(caption, parent_id) VALUES('Кофе', 9);
INSERT INTO CATS(caption, parent_id) VALUES('Гор. шок.', 9);
INSERT INTO CATS(caption, parent_id) VALUES('Другие напитки', 9);
INSERT INTO CATS(caption, parent_id) VALUES('Пластиковый', 13);
INSERT INTO CATS(caption, parent_id) VALUES('Десерты', 13);
INSERT INTO CATS(caption, parent_id) VALUES('Коктейли', 13);
INSERT INTO CATS(caption, parent_id) VALUES('Теплые', 15);
INSERT INTO CATS(caption, parent_id) VALUES('Освежающие', 15);
INSERT INTO CATS(caption, parent_id) VALUES('Горячие', 15);
INSERT INTO CATS(caption, parent_id) VALUES('Добавки', 19);
INSERT INTO CATS(caption, parent_id) VALUES('Еда', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Сендвичи', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Салаты', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Супы', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Паста/Ризотто', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Блины', 20);
INSERT INTO CATS(caption, parent_id) VALUES('С начинкой', 25);
INSERT INTO CATS(caption, parent_id) VALUES('Сладкие', 25);
INSERT INTO CATS(caption, parent_id) VALUES('Фритюр', 20);
INSERT INTO CATS(caption, parent_id) VALUES('Соусы', 20);
INSERT INTO CATS(caption, parent_id) VALUES(');