INSERT INTO GOODS(caption) VALUES ('Американо 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 1, 1);
INSERT INTO GOODS(caption) VALUES ('Американо 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (60, 2, 1);
INSERT INTO GOODS(caption) VALUES ('Американо 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (105, 3, 1);
INSERT INTO GOODS(caption) VALUES ('Американо на мол. 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (80, 4, 1);
INSERT INTO GOODS(caption) VALUES ('Американо на мол. 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (130, 5, 1);
INSERT INTO GOODS(caption) VALUES ('Американо на мол. 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (140, 6, 1);
INSERT INTO GOODS(caption) VALUES ('Капучино 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (80, 7, 1);
INSERT INTO GOODS(caption) VALUES ('Капучино 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (130, 8, 1);
INSERT INTO GOODS(caption) VALUES ('Капучино 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (140, 9, 1);
INSERT INTO GOODS(caption) VALUES ('Латте 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (80, 10, 1);
INSERT INTO GOODS(caption) VALUES ('Латте 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (130, 11, 1);
INSERT INTO GOODS(caption) VALUES ('Латте 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (140, 12, 1);
INSERT INTO GOODS(caption) VALUES ('Мокко 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 13, 1);
INSERT INTO GOODS(caption) VALUES ('Мокко 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (160, 14, 1);
INSERT INTO GOODS(caption) VALUES ('Мокко 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (170, 15, 1);
INSERT INTO GOODS(caption) VALUES ('Меланж 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 16, 1);
INSERT INTO GOODS(caption) VALUES ('Меланж 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (170, 17, 1);
INSERT INTO GOODS(caption) VALUES ('Меланж 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (190, 18, 1);
INSERT INTO GOODS(caption) VALUES ('Гор. шок. "Melange" 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (115, 19, 1);
INSERT INTO GOODS(caption) VALUES ('Гор. шок. "Melange" 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (179, 20, 1);
INSERT INTO GOODS(caption) VALUES ('Гор. шок. "Melange" 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (199, 21, 1);
INSERT INTO GOODS(caption) VALUES ('Гор. шок. "Classic" 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 22, 1);
INSERT INTO GOODS(caption) VALUES ('Какао 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (109, 23, 1);
INSERT INTO GOODS(caption) VALUES ('Какао 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (119, 24, 1);
INSERT INTO GOODS(caption) VALUES ('Айриш кофе 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (115, 25, 1);
INSERT INTO GOODS(caption) VALUES ('Айриш кофе 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (165, 26, 1);
INSERT INTO GOODS(caption) VALUES ('Айриш кофе 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (190, 27, 1);
INSERT INTO GOODS(caption) VALUES ('Гляссе 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 28, 1);
INSERT INTO GOODS(caption) VALUES ('Гляссе 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (115, 29, 1);
INSERT INTO GOODS(caption) VALUES ('Гляссе 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (135, 30, 1);
INSERT INTO GOODS(caption) VALUES ('Кофе "СССР" 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (85, 31, 1);
INSERT INTO GOODS(caption) VALUES ('Кофе "СССР" 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (139, 32, 1);
INSERT INTO GOODS(caption) VALUES ('Кофе "СССР" 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (149, 33, 1);
INSERT INTO GOODS(caption) VALUES ('"Milk & Honey" 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (55, 34, 0);
INSERT INTO GOODS(caption) VALUES ('"Milk & Honey" 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (79, 35, 0);
INSERT INTO GOODS(caption) VALUES ('"Milk & Honey" 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (89, 36, 0);
INSERT INTO GOODS(caption) VALUES ('"Baby milk" 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (50, 37, 0);
INSERT INTO GOODS(caption) VALUES ('"Baby milk" 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (75, 38, 0);
INSERT INTO GOODS(caption) VALUES ('"Baby milk" 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (85, 39, 0);
INSERT INTO GOODS(caption) VALUES ('Чайный латте 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (55, 40, 0);
INSERT INTO GOODS(caption) VALUES ('Чайный латте 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (80, 41, 0);
INSERT INTO GOODS(caption) VALUES ('Чайный латте 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (90, 42, 0);
INSERT INTO GOODS(caption) VALUES ('Чай 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (35, 43, 0);
INSERT INTO GOODS(caption) VALUES ('Чай 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (60, 44, 0);
INSERT INTO GOODS(caption) VALUES ('Чай 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (70, 45, 0);
INSERT INTO GOODS(caption) VALUES ('Эспрессо 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (60, 46, 1);
INSERT INTO GOODS(caption) VALUES ('Двойной эспрессо 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (90, 47, 1);
INSERT INTO GOODS(caption) VALUES ('Сок 8oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (50, 48, 0);
INSERT INTO GOODS(caption) VALUES ('Сок 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (75, 49, 0);
INSERT INTO GOODS(caption) VALUES ('Сок 16oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (95, 50, 0);
INSERT INTO GOODS(caption) VALUES ('Молоко 50мл');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (10, 51, 1);
INSERT INTO GOODS(caption) VALUES ('Сливки 50мл');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (20, 52, 1);
INSERT INTO GOODS(caption) VALUES ('Сироп 10мл');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (15, 53, 1);
INSERT INTO GOODS(caption) VALUES ('Взбитые сливки 15гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (15, 54, 1);
INSERT INTO GOODS(caption) VALUES ('Топпинг 20гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (20, 55, 1);
INSERT INTO GOODS(caption) VALUES ('Мёд 20гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (20, 56, 1);
INSERT INTO GOODS(caption) VALUES ('Сгущ.молоко 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (20, 57, 1);
INSERT INTO GOODS(caption) VALUES ('Мороженое 1порц');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (20, 58, 1);
INSERT INTO GOODS(caption) VALUES ('Маршмеллоу 1порц');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (15, 59, 1);
INSERT INTO GOODS(caption) VALUES ('Эспрессо 1порц');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES (30, 60, 1);

INSERT INTO GOODS(caption) VALUES('Фруктовый пунш Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(100, 61, 0);
INSERT INTO GOODS(caption) VALUES('Шоколад. время Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 62, 0);
INSERT INTO GOODS(caption) VALUES('Кокосовый остров Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(140, 63, 0);
INSERT INTO GOODS(caption) VALUES('День и ночь Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(180, 64, 0);
INSERT INTO GOODS(caption) VALUES('Кофе Тюр Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 65, 0);
INSERT INTO GOODS(caption) VALUES('Чай Ирл. Сливки Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(110, 66, 0);
INSERT INTO GOODS(caption) VALUES('Лед. Фрукт. чай Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(110, 67, 0);
INSERT INTO GOODS(caption) VALUES('Ледяной Латте Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(129, 68, 0);
INSERT INTO GOODS(caption) VALUES('Освежись Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 69, 0);
INSERT INTO GOODS(caption) VALUES('Сочный шоколад Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(130, 70, 0);
INSERT INTO GOODS(caption) VALUES('Лед/Гор клубника Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(129, 71, 0);
INSERT INTO GOODS(caption) VALUES('Кар-орех. Чудо Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 72, 0);
INSERT INTO GOODS(caption) VALUES('Клубн. в шок. Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(180, 73, 0);
INSERT INTO GOODS(caption) VALUES('Шейкератто Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(129, 74, 0);
INSERT INTO GOODS(caption) VALUES('Ромео Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(169, 75, 0);
INSERT INTO GOODS(caption) VALUES('Джульетта Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(179, 76, 0);
INSERT INTO GOODS(caption) VALUES('Энергия лета Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 77, 0);
INSERT INTO GOODS(caption) VALUES('Смузи фруктовый Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(100, 78, 0);
INSERT INTO GOODS(caption) VALUES('Фраппе Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 79, 0);
INSERT INTO GOODS(caption) VALUES('Мохито Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(169, 80, 0);
INSERT INTO GOODS(caption) VALUES('Молочный коктейль Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(100, 81, 0);
INSERT INTO GOODS(caption) VALUES('Пина колада  Pl');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(129, 82, 0);

INSERT INTO GOODS(caption) VALUES('Сендвич пол.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 83, 0);
INSERT INTO GOODS(caption) VALUES('Вафли');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(79, 84, 0);
INSERT INTO GOODS(caption) VALUES('Киш');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(70, 85, 0);
INSERT INTO GOODS(caption) VALUES('Пирог');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(70, 86, 0);
INSERT INTO GOODS(caption) VALUES('Шоколадка');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(10, 87, 0);
INSERT INTO GOODS(caption) VALUES('Макарон');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(59, 88, 0);
INSERT INTO GOODS(caption) VALUES('Корзинка');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(35, 89, 0);
INSERT INTO GOODS(caption) VALUES('Маффин');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(35, 90, 0);
INSERT INTO GOODS(caption) VALUES('Almondy');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 91, 0);
INSERT INTO GOODS(caption) VALUES('Шоколад ПК 65гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(60, 92, 0);
INSERT INTO GOODS(caption) VALUES('Шоколад ПК 180гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(180, 93, 0);
INSERT INTO GOODS(caption) VALUES('Мороженое с топ. 12oz');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(80, 94, 0);
INSERT INTO GOODS(caption) VALUES('Кола');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 95, 0);
INSERT INTO GOODS(caption) VALUES('Спрайт');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 96, 0);
INSERT INTO GOODS(caption) VALUES('Бонаква');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 97, 0);
INSERT INTO GOODS(caption) VALUES('Перье');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(100, 98, 0);
INSERT INTO GOODS(caption) VALUES('Витель');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(100, 99, 0);
INSERT INTO GOODS(caption) VALUES('Салат Греческий');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(210, 100, 0);
INSERT INTO GOODS(caption) VALUES('Салат теплый с кур.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(260, 101, 0);
INSERT INTO GOODS(caption) VALUES('Цезарь с курицей');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(250, 102, 0);
INSERT INTO GOODS(caption) VALUES('Салат с малос. неркой');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(270, 103, 0);
INSERT INTO GOODS(caption) VALUES('Бульон с кур. и яйцом');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(110, 104, 0);
INSERT INTO GOODS(caption) VALUES('Крем суп из шамп.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(180, 105, 0);
INSERT INTO GOODS(caption) VALUES('Суп охотничий');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(160, 106, 0);
INSERT INTO GOODS(caption) VALUES('Сырный крем-суп с вет.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(180, 107, 0);
INSERT INTO GOODS(caption) VALUES('Карбонара');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(230, 108, 0);
INSERT INTO GOODS(caption) VALUES('Паста с кур. и гр.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(250, 109, 0);
INSERT INTO GOODS(caption) VALUES('Ризотто с кур. и овощ.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(230, 110, 0);
INSERT INTO GOODS(caption) VALUES('Ризотто с морепр.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(280, 111, 0);
INSERT INTO GOODS(caption) VALUES('Сэндвич с вет. и сыр.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 112, 0);
INSERT INTO GOODS(caption) VALUES('Сэндвич с беконом');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 113, 0);
INSERT INTO GOODS(caption) VALUES('Сэндвич с кур.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 114, 0);
INSERT INTO GOODS(caption) VALUES('Сендвич с неркой');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 115, 0);
INSERT INTO GOODS(caption) VALUES('3D картошка');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 116, 0);
INSERT INTO GOODS(caption) VALUES('3D карт. с колб.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(150, 117, 0);
INSERT INTO GOODS(caption) VALUES('Карт. фри');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(120, 118, 0);
INSERT INTO GOODS(caption) VALUES('Карт. дольки');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(120, 119, 0);
INSERT INTO GOODS(caption) VALUES('Наггетсы');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(120, 120, 0);
INSERT INTO GOODS(caption) VALUES('Сыр. палочки');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(140, 121, 0);
INSERT INTO GOODS(caption) VALUES('Майонез 40г');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 122, 0);
INSERT INTO GOODS(caption) VALUES('Кетчуп 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 123, 0);
INSERT INTO GOODS(caption) VALUES('Барбекю 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 124, 0);
INSERT INTO GOODS(caption) VALUES('Сырный 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 125, 0);
INSERT INTO GOODS(caption) VALUES('Цезарь 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 126, 0);
INSERT INTO GOODS(caption) VALUES('Блин. прост.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(190, 127, 0);
INSERT INTO GOODS(caption) VALUES('Блин. вет. и сыр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(55, 128, 0);
INSERT INTO GOODS(caption) VALUES('Блин. кур. и сыр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(60, 129, 0);
INSERT INTO GOODS(caption) VALUES('Блин. гр. жуль.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(45, 130, 0);
INSERT INTO GOODS(caption) VALUES('Блин. кур. и гр. жуль');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(55, 131, 0);
INSERT INTO GOODS(caption) VALUES('Блин. нерка');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(75, 132, 0);
INSERT INTO GOODS(caption) VALUES('Блин. гов. и рис');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(60, 133, 0);
INSERT INTO GOODS(caption) VALUES('Блин. рататуй');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(45, 134, 0);
INSERT INTO GOODS(caption) VALUES('Блин. творог');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(45, 135, 0);
INSERT INTO GOODS(caption) VALUES('Блин. вар. сгущ.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(40, 136, 0);
INSERT INTO GOODS(caption) VALUES('Блин. ябл. и апель.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(45, 137, 0);
INSERT INTO GOODS(caption) VALUES('Блин. Бубль-гум');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(45, 138, 0);
INSERT INTO GOODS(caption) VALUES('Блин. тв. крем и ягоды');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(55, 139, 0);
INSERT INTO GOODS(caption) VALUES('Блин. тв. крем и фрукты');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 140, 0);
INSERT INTO GOODS(caption) VALUES('Сметана 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 141, 0);
INSERT INTO GOODS(caption) VALUES('Сгущ. 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(20, 142, 0);
INSERT INTO GOODS(caption) VALUES('Соус карам.-слив.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 143, 0);
INSERT INTO GOODS(caption) VALUES('Соус карам.-апельс.');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(30, 144, 0);
INSERT INTO GOODS(caption) VALUES('Джем 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(50, 145, 0);
INSERT INTO GOODS(caption) VALUES('Ягодный 40гр');
INSERT INTO PRICED_GOODS(price, good_id, action_able) VALUES(40, 146, 0);